#
# Makefile / Command Line Arguments
#
# John O'Connell / CS5600 / Northeastern University
# Fall 2023 / Sep 12, 2023
#
#

all: arger-oconnell

arger-oconnell: arger-oconnell.c arger-oconnell-helper.c
	@gcc arger-oconnell.c arger-oconnell-helper.c -o arger-oconnell

clean:
	@rm -f arger-oconnell
	@touch arger-oconnell.c arger-oconnell-helper.c
