#
# Makefile / Random Number Generation
#
# John O'Connell / CS5600 / Northeastern University
# Fall 2023 / Sep 16, 2023
#
#

all: genRand


genRand: genRand-oconnell.c
	@gcc genRand-oconnell.c genRand-helper.c -o genRand


clean:
	@rm -f genRand
	@touch genRand-oconnell.c genRand-helper.c

