#
# Makefile / Program in C
#
# John O'Connell / CS5600 / Northeastern University
# Fall 2023 / Sep 8, 2023
#
#

all: OConnellJ.CS5600.LearnC

OConnellJ.CS5600.LearnC: OConnellJ.CS5600.LearnC.c mpg2km.c
	@gcc OConnellJ.CS5600.LearnC.c mpg2km.c -o CS5600.LearnC

clean:
	@rm -f CS5600.LearnC
	@touch OConnellJ.CS5600.LearnC.c mpg2km.c

