#
# Makefile / Threads
#
# John O'Connell / CS5600 / Northeastern University
# Fall 2023 / Oct 2, 2023
#
#

all: threads

threads: OConnellJ.CS5600.F23.c
	@gcc OConnellJ.CS5600.F23.c -o threads

clean:
	@rm -f threads
	@touch OConnellJ.CS5600.F23.c
