#
# Makefile / Practicum 2
#
# John O'Connell / CS5600 / Northeastern University
# Fall 2023 / Nov 28, 2023
#
#

all: server client

server: server.c
	gcc server.c -o server

client: client.c
	gcc client.c -o client

clean:
	rm -f server client
