#
# Makefile / Random Word Generation
#
# John O'Connell / CS5600 / Northeastern University
# Fall 2023 / Oct 8, 2023
#
#

all: genRandWord


genRandWord: genRandWord-oconnell.c
	@gcc genRandWord-oconnell.c genRandWord-helper.c -o genRandWord


clean:
	@rm -f genRandWord
	@touch genRandWord-oconnell.c genRandWord-helper.c

